using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using Microsoft.Web.WebView2.Core;

namespace WinRT;

internal static class RcwFallbackInitializer
{
	[ModuleInitializer]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2AcceleratorKeyPressedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2BasicAuthenticationRequestedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2BasicAuthenticationResponse))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2BrowserExtension))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2BrowserProcessExitedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2Certificate))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ClientCertificate))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ClientCertificateRequestedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2CompositionController))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ContentLoadingEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ContextMenuItem))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ContextMenuRequestedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ContextMenuTarget))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2Controller))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ControllerOptions))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ControllerWindowReference))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2Cookie))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2CookieManager))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2CustomSchemeRegistration))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2DOMContentLoadedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2DevToolsProtocolEventReceivedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2DevToolsProtocolEventReceiver))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2DownloadOperation))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2DownloadStartingEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2Environment))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2EnvironmentOptions))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ExecuteScriptResult))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2File))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2FileSystemHandle))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2Frame))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2FrameCreatedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2FrameInfo))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2HttpHeadersCollectionIterator))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2HttpRequestHeaders))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2HttpResponseHeaders))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2LaunchingExternalUriSchemeEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2MoveFocusRequestedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2NavigationCompletedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2NavigationStartingEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2NewWindowRequestedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2NonClientRegionChangedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2PermissionRequestedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2PermissionSetting))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2PointerInfo))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2PrintSettings))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ProcessExtendedInfo))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ProcessFailedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ProcessInfo))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2Profile))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ScriptDialogOpeningEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ScriptException))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2ServerCertificateErrorDetectedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2Settings))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2SharedBuffer))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2SourceChangedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2WebMessageReceivedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2WebResourceRequest))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2WebResourceRequestedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2WebResourceResponse))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2WebResourceResponseReceivedEventArgs))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2WebResourceResponseView))]
	[DynamicDependency(DynamicallyAccessedMemberTypes.NonPublicConstructors, typeof(CoreWebView2WindowFeatures))]
	public static void InitializeRcwFallback()
	{
	}
}
